# from https://speciationgenomics.github.io/Treemix/
library(RColorBrewer)
library(OptM)
source("~/Softwares/Treemix/treemix/src/plotting_funcs.R")

setwd("./") # of course this needs to be adjusted
prefix="SnovacapitalisOutgroup"

####################################
######## with treemix codes ########
####################################
svg(paste0(prefix,"0_rep1.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"0_rep1"))
dev.off()
svg(paste0(prefix,"0_rep2.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"0_rep2"))
dev.off()
svg(paste0(prefix,"0_rep3.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"0_rep3"))
dev.off()

svg(paste0(prefix,"1_rep1.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"1_rep1"))
dev.off()
svg(paste0(prefix,"1_rep2.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"1_rep2"))
dev.off()
svg(paste0(prefix,"1_rep3.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"1_rep3"))
dev.off()

svg(paste0(prefix,"2_rep1.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"2_rep1"))
dev.off()
svg(paste0(prefix,"2_rep2.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"2_rep2"))
dev.off()
svg(paste0(prefix,"2_rep3.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"2_rep3"))
dev.off()

svg(paste0(prefix,"3_rep1.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"3_rep1"))
dev.off()
svg(paste0(prefix,"3_rep2.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"3_rep2"))
dev.off()
svg(paste0(prefix,"3_rep3.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"3_rep3"))
dev.off()

svg(paste0(prefix,"4_rep1.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"4_rep1"))
dev.off()
svg(paste0(prefix,"4_rep2.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"4_rep2"))
dev.off()
svg(paste0(prefix,"4_rep3.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"4_rep3"))
dev.off()

svg(paste0(prefix,"5_rep1.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"5_rep1"))
dev.off()
svg(paste0(prefix,"5_rep2.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"5_rep2"))
dev.off()
svg(paste0(prefix,"5_rep3.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"5_rep3"))
dev.off()

svg(paste0(prefix,"6_rep1.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"6_rep1"))
dev.off()
svg(paste0(prefix,"6_rep2.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"6_rep2"))
dev.off()
svg(paste0(prefix,"6_rep3.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"6_rep3"))
dev.off()

svg(paste0(prefix,"7_rep1.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"7_rep1"))
dev.off()
svg(paste0(prefix,"7_rep2.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"7_rep2"))
dev.off()
svg(paste0(prefix,"7_rep3.svg"),10,10)
plot_tree(cex=0.8,paste0(prefix,"7_rep3"))
dev.off()


# plot residual 
svg(paste0(prefix,"_mix0residual.svg"),10,10)
plot_resid(stem=paste0(prefix,"0_rep1"),pop_order="plotorder.txt")
dev.off()
svg(paste0(prefix,"_mix1residual.svg"),10,10)
plot_resid(stem=paste0(prefix,"1_rep1"),pop_order="plotorder.txt")
dev.off()
svg(paste0(prefix,"_mix2residual.svg"),10,10)
plot_resid(stem=paste0(prefix,"2_rep1"),pop_order="plotorder.txt")
dev.off()
svg(paste0(prefix,"_mix3residual.svg"),10,10)
plot_resid(stem=paste0(prefix,"3_rep1"),pop_order="plotorder.txt")
dev.off()
svg(paste0(prefix,"_mix4residual.svg"),10,10)
plot_resid(stem=paste0(prefix,"4_rep1"),pop_order="plotorder.txt")
dev.off()
svg(paste0(prefix,"_mix5residual.svg"),10,10)
plot_resid(stem=paste0(prefix,"5_rep1"),pop_order="plotorder.txt")
dev.off()
svg(paste0(prefix,"_mix6residual.svg"),10,10)
plot_resid(stem=paste0(prefix,"6_rep1"),pop_order="plotorder.txt")
dev.off()
svg(paste0(prefix,"_mix7residual.svg"),10,10)
plot_resid(stem=paste0(prefix,"7_rep1"),pop_order="plotorder.txt")
dev.off()

#best model fit
optM("./",orientagraph=F,"bestmodelfit.tsv",method="Evanno")
