/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u BocainaSerradoMarRJ1_lin4.d5.D45.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u Caparao_lin3.d5.D50.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u CentroLestePR1_lin7.d5.D45.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u CentroOesteSC1_lin7.d5.D45.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u CunhaSerradoMarRJ2_lin4.d5.D45.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u DevonianaPR3_lin5.d5.D45.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u DevonianaPR8.d10.D90.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u ExtremoSulRS3_lin7.d5.D45.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u NorteMantiqueira3_lin3.d6.D60.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u NortePR3_lin5.d6.D60.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u NortePR_lin7.d6.D60.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u Sdiamantinensis.d7.D70.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u SerradaOuricana_lin1.d5.D45.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u SerradasLontra4_lin1.d6.D60.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u SerradosOrgaos3_lin2.d3.D30.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u Snovacapitalis.d10.D90.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u Spachecoi.d10.D90.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u Spetrophilus.d5.D50.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u Ssuperciliaris.d3.D30.diploid.psmc
/media/labgenoma5/DATAPART1/bandriola/Softwares/psmc/utils/psmc_plot.pl -u SulMantiqueira3_lin3.d7.D66.diploid.psmc
