#! /bin/bash
####step 3
echo "step 3"
cut -f 1,2 ./Step1to2/output_EleoindigoticusUCE_final.bam_masked.fa > output_EleoindigoticusUCE_final.GENOME
cut -f 1,2 ./Step1to2/output_EleopsychopompusUCE1_final.bam.fa.bam_masked.fa.fai > output_EleopsychopompusUCE1_final.GENOME
cut -f 1,2 ./Step1to2/output_Sdiamantinensis127_final.bam.fa.bam_masked.fa.fai > output_Sdiamantinensis127_final.GENOME
cut -f 1,2 ./Step1to2/output_SiraiensisUCE_final.bam.fa.bam_masked.fa.fai > output_SiraiensisUCE_final.GENOME
cut -f 1,2 ./Step1to2/output_Snovacapitalis152_lin_final.bam.fa.bam_masked.fa.fai > output_Snovacapitalis152_lin_final.GENOME
cut -f 1,2 ./Step1to2/output_Spachecoi154_final.bam.fa.bam_masked.fa.fai > output_Spachecoi154_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae101_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae101_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae103_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae103_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae106_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae106_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae107_lin5_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae107_lin5_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae109_lin5_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae109_lin5_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae110_lin5_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae110_lin5_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae113_lin3_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae113_lin3_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae114_lin3_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae114_lin3_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae116_lin3_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae116_lin3_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae117_lin1_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae117_lin1_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae118_lin1_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae118_lin1_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae119_lin1_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae119_lin1_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae120_lin1_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae120_lin1_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae121_lin1_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae121_lin1_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae122_lin6_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae122_lin6_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae123_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae123_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae12_lin3_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae12_lin3_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae139_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae139_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae13_lin3_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae13_lin3_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae140_lin5_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae140_lin5_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae14_lin3_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae14_lin3_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae15_lin3_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae15_lin3_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae16_lin4_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae16_lin4_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae19_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae19_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae1_lin4_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae1_lin4_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae23_lin5_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae23_lin5_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae28_lin5_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae28_lin5_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae2_lin4_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae2_lin4_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae30_lin5_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae30_lin5_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae32_lin5_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae32_lin5_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae33_lin_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae33_lin_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae38_lin3_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae38_lin3_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae3_lin4_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae3_lin4_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae43_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae43_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae46_lin1_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae46_lin1_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae47_lin1_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae47_lin1_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae48_lin1_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae48_lin1_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae49_lin1_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae49_lin1_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae4_lin4_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae4_lin4_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae52_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae52_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae54_lin6_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae54_lin6_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae56_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae56_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae57_lin5_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae57_lin5_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae59_lin5_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae59_lin5_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae5_lin4_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae5_lin4_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae64_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae64_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae68_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae68_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae69_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae69_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae6_lin2_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae6_lin2_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae71_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae71_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae72_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae72_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae73_lin3_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae73_lin3_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae74_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae74_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae75_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae75_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae83_lin2_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae83_lin2_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae85_lin5_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae85_lin5_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae86_lin5_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae86_lin5_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae87_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae87_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae8_lin2_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae8_lin2_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae95_lin7_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae95_lin7_final.GENOME
cut -f 1,2 ./Step1to2/output_Sspeluncae9_lin3_final.bam.fa.bam_masked.fa.fai > output_Sspeluncae9_lin3_final.GENOME
cut -f 1,2 ./Step1to2/output_Ssuperciliaris_final.bam.fa.bam_masked.fa.fai > output_Ssuperciliaris_final.GENOME
